const app=document.querySelector('#app'); const qs=new URLSearchParams(location.search); let mode=qs.get('mode'); let code=localStorage.quizCode||''; let playerId=localStorage.quizPlayer||''; let selected=null; let last='';
document.head.insertAdjacentHTML('beforeend',`<style>
:root{--coral:#FF595E;--blue:#096790;--sherpa:#023444}body{background:#f5f7f8!important;color:var(--sherpa)!important}.card{border-top:4px solid var(--coral)!important}.brand-inline{display:block;width:170px;height:auto;margin:0 0 20px}.card h1,.card h2{color:var(--sherpa)!important}.card button:not(:disabled){background:var(--blue)!important;color:#fff!important}.card button.secondary{background:#e7f1f5!important;color:var(--sherpa)!important}.code{color:var(--coral)!important}.pill{background:#fff0f0!important;color:var(--coral)!important}.option{background:#e7f1f5!important;color:var(--sherpa)!important}.option.selected{outline-color:var(--coral)!important}</style>`);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shell(x){app.innerHTML=`<div class="wrap">${x}</div>`} function err(e){alert(e.message||e)}
async function api(path,opt={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opt});const d=await r.json();if(!r.ok)throw Error(d.error||'Chyba');return d}
function brand(){return `<img src="/seyfor-logo.png" alt="Seyfor" style="display:block;width:170px!important;height:auto!important;max-width:170px!important;margin:0 0 20px;object-fit:contain">`}
function home(){shell(`<div class="card">${brand()}<span class="pill">SALES TEAM</span><h1>Sales TB Sales a přátel obchodu</h1><p class="muted">Vyber si režim.</p><div class="row"><button onclick="location.search='?mode=host'">Moderátor</button><button class="secondary" onclick="location.search='?mode=player'">Hráč</button></div></div>`)}
async function host(){if(!code){const d=await api('/api/create',{method:'POST'});code=d.code;localStorage.quizCode=code} renderHost(await state('host'));}
async function state(role){return api(`/api/state?code=${encodeURIComponent(code)}&role=${role}&playerId=${playerId}`)}
function renderHost(s){const q=s.question; let body=`<div class="card">${brand()}<span class="pill">MODERÁTOR</span><h1>Sales TB Sales a přátel obchodu</h1><p>Místnost pro hráče:</p><div class="code">${s.code}</div><p class="muted">Hráči otevřou tuto adresu na mobilu a zadají kód místnosti.</p><p><b>${location.origin}/?mode=player</b></p><hr><p>Stav: <b>${s.phase==='lobby'?'čeká se na hráče':s.phase==='question'?'otázka probíhá':s.phase==='results'?'výsledky':'konec'}</b> · ${Math.max(0,s.index+1)}/${s.total}</p>`;
if(s.phase==='lobby') body+=`<div class="row"><button onclick="act('start')">Spustit kvíz</button></div>`; else if(s.phase==='question') body+=`<div class="card"><div class="question">${esc(q.text)}</div><div class="grid">${q.options.map((o,i)=>`<button class="option" disabled>${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}</div><p>Odpovědělo: ${s.counts.reduce((a,b)=>a+b,0)} hráčů</p><button onclick="act('reveal')">Uzavřít odpovědi a zobrazit výsledky</button></div>`; else if(s.phase==='results') body+=`<div class="card"><div class="question">Správně: ${esc(q.options[q.answer])}</div><p>Počet odpovědí: ${s.counts.join(' · ')}</p><button onclick="act('next')">${s.index+1===s.total?'Zobrazit konečné pořadí':'Další otázka'}</button></div>`; else body+=`<div class="card"><h2>🏆 Konečné pořadí</h2>${Object.entries(s.scores).sort((a,b)=>b[1]-a[1]).map(([t,v],i)=>`<div class="score"><b>${i+1}. ${esc(t)}</b><span>${v} b</span></div>`).join('')}</div>`;
body+=`</div><div class="card"><h2>Týmy</h2>${Object.entries(s.scores).map(([t,v])=>`<div class="score"><b>${esc(t)}</b><span>${v} b · ${s.players.filter(p=>p.team===t).map(p=>esc(p.name)).join(', ')||'—'}</span></div>`).join('')}</div>`; shell(body);}
async function act(action){try{renderHost(await api('/api/action',{method:'POST',body:JSON.stringify({code,action})}))}catch(e){err(e)}}
async function player(){if(!playerId){shell(`<div class="card"><span class="pill">HRÁČ</span><h1>Připojit se ke kvízu</h1><form id="join"><input name="code" placeholder="Kód místnosti" required maxlength="5"><input name="name" placeholder="Tvoje jméno" required><select name="team">${['Modří','Červení','Zelení','Žlutí','Fialoví','Oranžoví','Černí','Bílí'].map(t=>`<option>${t}</option>`).join('')}</select><button>Připojit se</button></form></div>`);document.querySelector('#join').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);code=f.get('code').toUpperCase();const d=await api('/api/join',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});playerId=d.playerId;localStorage.quizCode=code;localStorage.quizPlayer=playerId;renderPlayer(d)}catch(x){err(x)}};return} try{renderPlayer(await state('player'))}catch(e){localStorage.clear();playerId='';player()} }
function renderPlayer(s){let body=`<div class="card">${brand()}<span class="pill">${esc(s.code)}</span><h1>Sales TB Sales a přátel obchodu</h1><p>Tvůj tým: <b>${esc(s.playerTeam||'—')}</b></p>`;if(s.phase==='lobby')body+=`<p>Čekáme, až moderátor spustí hru…</p>`;else if(s.phase==='question'){body+=`<div class="question">${esc(s.question.text)}</div><div class="grid">${s.question.options.map((o,i)=>`<button class="option ${selected===i?'selected':''}" onclick="choose(${i})" ${s.answered?'disabled':''}>${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}</div><p>${s.answered?'Odpověď odeslána. Čekej na výsledky.':'Vyber jednu odpověď.'}</p>`}else if(s.phase==='results')body+=`<h2>Výsledky kola</h2><p>Správná odpověď: <b>${esc(s.question.options[s.question.answer])}</b></p>`;else body+=`<h2>Hotovo!</h2><p>Počkej na vyhlášení vítězů.</p>`;body+=`</div><div class="card"><h2>Průběžné skóre</h2>${Object.entries(s.scores).sort((a,b)=>b[1]-a[1]).map(([t,v])=>`<div class="score"><b>${esc(t)}</b><span>${v} b</span></div>`).join('')}</div>`;shell(body)}
async function choose(i){selected=i;try{renderPlayer(await api('/api/action',{method:'POST',body:JSON.stringify({code,action:'answer',playerId,option:i})}))}catch(e){err(e)}}
window.act=act; window.choose=choose;
if(mode==='host')host(); else if(mode==='player')player(); else home(); setInterval(async()=>{if(mode==='host'&&code){try{renderHost(await state('host'))}catch{}} if(mode==='player'&&playerId){try{renderPlayer(await state('player'))}catch{}}},1500);
